import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "TODO: Boda Natasha y Emilio",
  description: "TODO: Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      
      <body className="font-montserrat">{children}</body>
    </html>
  );
}
